# Generated by Django 4.1.4 on 2022-12-28 07:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('created_at', models.TimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('text', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('resp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('like', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], default='like', max_length=10)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='api.post')),
            ],
        ),
    ]
