# Generated by Django 4.1.4 on 2022-12-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_like_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Likemodel',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='Postmodel',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Usermodel',
        ),
    ]
