# Generated by Django 4.1.4 on 2022-12-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_likemodel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='user_id',
        ),
    ]
