# Generated by Django 4.1.4 on 2022-12-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_likemodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='like',
            field=models.CharField(choices=[('like', 'like'), ('like', 'like')], default='like', max_length=10),
        ),
    ]
